### ISSUE TITLE
Auf einmal keine Funktion mehr und dann keine Geräte

### ISSUE THREAD

**Issue by ManuelKlimek** [iobroker-community-adapters/ioBroker.harmony#140]
Morgen

Ich hab 2 Gerät im Harmony Hub diese reagierten vorgestern dann einfach nicht mehr über den Adapter.
Via Harmony App lassen sie sich weiterhin steuern nach löschen des Adapters und neuinstallation werden nun auch keine Geräte mehr angezeigt.

**Comment by MedizinPumPer** [comment]
Schließe mich dem ganzen an, erhalte auch keine geräte mehr. 
System ist Docker auf einem Synology NAS. Ports sind freigegeben (61991)

**Comment by ManuelKlimek** [comment]
> Schließe mich dem ganzen an, erhalte auch keine geräte mehr. System ist Docker auf einem Synology NAS. Ports sind freigegeben (61991)

hatte ich nicht mal raspy iob fertig

**Comment by mcm1957** [comment]
I suggest to open a Topic at forum. This might lead to a faster solution if the problem is not caused by some codeing error.

If you did not update teh adapter at time of problem arises (or short time before) its mor likely that a network problem causes to troubles. Harmony uses UDP broadcast packages. So those packats must not be blocked by router / switch.
