### ISSUE TITLE
Adapter 1.5.0 stop working with JS-Controller 7.0.3

### ISSUE THREAD

**Issue by cmdrtom** [iobroker-community-adapters/ioBroker.harmony#214]
I have updated my iobroker to js-controller 7.0.3. The harmony adapter stops working after the update. Adapter shows all condition green, but my harmony hub is not discovered.

![image](https://github.com/user-attachments/assets/5345b0da-d4e7-4506-a585-4b317a5fb0ee)

**Comment by mcm1957** [comment]
Thanks for debug log. Sad to say that it does not show any problem.

As there have been no changes between js-controller 6 and js-controller 7 which obviously could cause this problem, please open a topic at iobroker forum (https://forum.iobroker.net) and post a link here so that we can get an isea if this problem effects more users.

And for completness: Did you update any other component at the same time?
Which js.controller did you use beforw when harmony was working?
Did you update O/S or node ?

**Comment by mcm1957** [comment]
The following topic at forum looks related to this issue
And most likely cdrtom and tom0 at forum are identical.

So I will close here as the problem seems to be solved according to linked forum topic.
