### ISSUE TITLE
Harmony Hub cannot be found after adding a second IP-Adress (Docker)

### ISSUE THREAD

**Issue by Kunibert-007** [iobroker-community-adapters/ioBroker.harmony#63]
For my ioBroker-Docker-Image I need a second IP-Adress. After adding it I can't reach the Harmony Hub anymore and in the options I can't specify the right network. Other adapters with network access have no problem.

My configuration:
Buanet Docker-Image for ioBroker on Synology NAS
Node 10.18.0
Js-controller 2.26
Version 1.22 from Harmony-Adapter

IP-Adress Synology: 192.168.0.3
IP-Adress ioBroker (MACVLAN): 192.168.0.30
IP-Adress Synology Docker-LAN: 172.20.10.1
IP-Adress ioBroker Docker-LAN: 172.20.10.3
IP-Adress Harmony Hub: 192.168.0.71

Log from ioBroker:

![image](https://user-images.githubusercontent.com/35669927/72375967-606bc700-370d-11ea-8c70-03ad26540227.png)

Don't know how to say the adapter he has to search in the MACVLAN-Network...

**Comment by AndyGR42** [comment]
Same issue here. It looks like the adapter ignores any dedicated IP adress.

**Comment by stratohe** [comment]
I basically have the same issue with one more complication:

The Harmony Hub is in a different VLAN than the docker host. So i have a chain like : DockerLan 172.x.x.x -> DocherHostLan 10.2.x.x and then IOT Lan 10.3.x.x

It is not possible to get the broadcasts over 2 segmenst. Could you please midify in a way where you can specify the IP of the Hub?

**Comment by David91919** [comment]
Same issue here, iobroker in docker can't find the hub no matter what I try

**Comment by pforrmi** [comment]
Same issue... Sadly the plugin is not usable with docker.

**Comment by baerengraben** [comment]
I have been using the harmony adapter for several years now and am very satisfied with it. When using Adapter and Hub in the same Subnet everything works like a charm. 

NOW: As part of security improvements, I have put my WLAN in its own subnet.  So the Harmony Hub (192.168.10.x) is now in a different subnet than the ioBroker (192.168.3.x).

The firewall configuration is set:
1. Harmony Hub has access to a DHCP server that provides an IP address and a valid gateway to the Internet.
2. Multicasts can propagate across subnets (UDP multicast to the group 224.0.0.1 on port 5224).
3. TCP traffic on port 8088 can propagate across subnets.

Nevertheless, the Harmony adapter does not find the hub. No matter how I configure the Adapter subnet (config). Some seem to have success with entering the IP (192.168.10.x) directly as the subnet. But that does not work either for me.

I'm sure the hub can communicate with the ioBroker's network (Hub to fakeRoker on same ioBroker still works). It just seems to be a problem with discovery. Is there any way to configure the hub itself directly so that it can operate without discovery first?

**Comment by mcm1957** [comment]
As this issue is ruther old, I will close here.
Please open a new issue if problem still exists and add all relevant release informations:
- adapter
- js-controller
- admin
- node
- o/s
